-- rule_based_logic for the four exercises, generated by scratch/export_web_logic.py from SeniorProject 2695984 on 2026-10-04.
-- Do not edit by hand: change the Python and re-run the export.

update public.exercises set rule_based_logic = $logic${
  "source": "generated by scratch/export_web_logic.py from SeniorProject 2695984",
  "state_machine": {
    "states": [
      "Idle",
      "Concentric",
      "Inflection",
      "Eccentric"
    ],
    "thresholds": {
      "thr_standing": 160.0,
      "thr_inflection": 120.0,
      "thr_descending": 150.0,
      "hysteresis_buffer": 10.0,
      "consecutive_frames_req": 3
    },
    "arming": {
      "joints": [
        "hip",
        "knee",
        "ankle"
      ],
      "ready_tilt_min": null,
      "ready_tilt_max": 30.0
    },
    "confidence_joints": [
      "hip",
      "knee",
      "ankle"
    ]
  },
  "placement": {
    "yaw_center": 45.0,
    "yaw_tol": 12.0
  },
  "rules": [
    {
      "name": "partial_squat",
      "check": "partial_squat",
      "priority": 1,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "depth_target": 100.0
      },
      "messages": {
        "en": "Lower to 90 degrees"
      },
      "highlight_joints": [
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    },
    {
      "name": "knee_valgus",
      "check": "knee_valgus",
      "priority": 2,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "parallel_max": 11.0
      },
      "messages": {
        "en": "Push knees out"
      },
      "highlight_joints": [
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    },
    {
      "name": "knee_varus",
      "check": "knee_varus",
      "priority": 3,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "parallel_max": 8.0
      },
      "messages": {
        "en": "Keep knees in line"
      },
      "highlight_joints": [
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    },
    {
      "name": "rounded_back",
      "check": "rounded_back",
      "priority": 4,
      "scope": "frame",
      "debounce_frames": 10,
      "threshold": {
        "tilt_max": 35.0
      },
      "messages": {
        "en": "Keep back straight"
      },
      "highlight_joints": [
        "left_shoulder",
        "right_shoulder",
        "left_hip",
        "right_hip"
      ]
    }
  ]
}$logic$::jsonb
where engine_key = 'squat';

update public.exercises set rule_based_logic = $logic${
  "source": "generated by scratch/export_web_logic.py from SeniorProject 2695984",
  "state_machine": {
    "states": [
      "Idle",
      "Concentric",
      "Inflection",
      "Eccentric"
    ],
    "thresholds": {
      "thr_standing": 0.9,
      "thr_inflection": 0.54,
      "thr_descending": 0.85,
      "hysteresis_buffer": 0.1,
      "consecutive_frames_req": 3
    },
    "arming": {
      "joints": [
        "shoulder",
        "elbow",
        "wrist"
      ],
      "ready_tilt_min": 60.0,
      "ready_tilt_max": null
    },
    "confidence_joints": [
      "shoulder",
      "elbow",
      "wrist"
    ]
  },
  "placement": {
    "yaw_center": 45.0,
    "yaw_tol": 25.0
  },
  "rules": [
    {
      "name": "hip_sag_or_pike",
      "check": "hip_sag_or_pike",
      "priority": 1,
      "scope": "frame",
      "debounce_frames": 10,
      "threshold": {
        "align_min": 160.0
      },
      "messages": {
        "en": "Body not straight"
      },
      "highlight_joints": [
        "left_shoulder",
        "right_shoulder",
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    },
    {
      "name": "partial_pushup",
      "check": "partial_pushup",
      "priority": 2,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "floor_bar_max": 0.54
      },
      "messages": {
        "en": "Lower Your Chest"
      },
      "highlight_joints": [
        "left_shoulder",
        "right_shoulder",
        "left_elbow",
        "right_elbow",
        "left_wrist",
        "right_wrist"
      ]
    }
  ]
}$logic$::jsonb
where engine_key = 'pushup';

update public.exercises set rule_based_logic = $logic${
  "source": "generated by scratch/export_web_logic.py from SeniorProject 2695984",
  "state_machine": {
    "states": [
      "Idle",
      "Concentric",
      "Inflection",
      "Eccentric"
    ],
    "thresholds": {
      "thr_standing": 155.0,
      "thr_inflection": 105.0,
      "thr_descending": 145.0,
      "hysteresis_buffer": 12.0,
      "consecutive_frames_req": 3,
      "lunge_start_split_min": 58.0
    },
    "arming": {
      "joints": [
        "hip",
        "knee",
        "ankle"
      ],
      "ready_tilt_min": null,
      "ready_tilt_max": 30.0
    },
    "confidence_joints": [
      "hip",
      "knee",
      "ankle"
    ]
  },
  "placement": {
    "yaw_center": 75.0,
    "yaw_tol": 10.0
  },
  "rules": [
    {
      "name": "shallow_lunge",
      "check": "shallow_lunge",
      "priority": 1,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "front_shallow_max": 105.0
      },
      "messages": {
        "en": "Lower your front knee"
      },
      "highlight_joints": [
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    },
    {
      "name": "excessive_front_knee_flexion",
      "check": "excessive_front_knee_flexion",
      "priority": 2,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "front_deep_min": 70.0
      },
      "messages": {
        "en": "Raise your front knee"
      },
      "highlight_joints": [
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    },
    {
      "name": "forward_trunk_lean",
      "check": "forward_trunk_lean",
      "priority": 3,
      "scope": "frame",
      "debounce_frames": 10,
      "threshold": {
        "tilt_max": 20.0
      },
      "messages": {
        "en": "Keep Torso Upright"
      },
      "highlight_joints": [
        "left_shoulder",
        "right_shoulder",
        "left_hip",
        "right_hip"
      ]
    },
    {
      "name": "straight_back_leg",
      "check": "straight_back_leg",
      "priority": 4,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "back_max_min": 120.0,
        "front_target": 105.0
      },
      "messages": {
        "en": "Bend your back knee toward the floor"
      },
      "highlight_joints": [
        "left_hip",
        "right_hip",
        "left_knee",
        "right_knee",
        "left_ankle",
        "right_ankle"
      ]
    }
  ]
}$logic$::jsonb
where engine_key = 'lunge';

update public.exercises set rule_based_logic = $logic${
  "source": "generated by scratch/export_web_logic.py from SeniorProject 2695984",
  "state_machine": {
    "states": [
      "Idle",
      "Concentric",
      "Inflection",
      "Eccentric"
    ],
    "thresholds": {
      "thr_standing": 155.0,
      "thr_inflection": 55.0,
      "thr_descending": 140.0,
      "hysteresis_buffer": 15.0,
      "consecutive_frames_req": 3,
      "start_descent_delta": 25.0,
      "min_side_score": 0.3
    },
    "arming": null,
    "confidence_joints": [
      "shoulder",
      "elbow",
      "wrist"
    ]
  },
  "placement": {
    "yaw_center": 45.0,
    "yaw_tol": 12.0
  },
  "rules": [
    {
      "name": "elbow_flare",
      "check": "elbow_flare",
      "priority": 1,
      "scope": "frame",
      "debounce_frames": 10,
      "threshold": {
        "flare_max": 45.0
      },
      "messages": {
        "en": "Keep Elbows at Your Sides"
      },
      "highlight_joints": [
        "left_shoulder",
        "right_shoulder",
        "left_elbow",
        "right_elbow",
        "left_hip",
        "right_hip"
      ]
    },
    {
      "name": "partial_curl",
      "check": "partial_curl",
      "priority": 2,
      "scope": "rep",
      "debounce_frames": 1,
      "threshold": {
        "flex_target": 55.0,
        "ext_target": 145.0
      },
      "messages": {
        "en": "Full range of motion"
      },
      "highlight_joints": [
        "left_shoulder",
        "right_shoulder",
        "left_elbow",
        "right_elbow",
        "left_wrist",
        "right_wrist"
      ]
    }
  ]
}$logic$::jsonb
where engine_key = 'dumbbell_biceps_curls';

-- Guide text: the camera sentences match the placement gate (the angle each exercise is
-- judged from) and three form sentences match the current rules. Drafts from
-- WEB_APP_PORT.md section 6.3, pending review by Vern and the physiotherapy experts.
-- The second paragraph is the start sequence of the ready gate.

update public.exercises set guide_text = $guide$Stand with your feet shoulder-width apart and pointing forward, knees in line with the feet, arms out in front or crossed at the chest. Sit the hips back and down until the thighs are at least parallel to the floor, keeping the chest up and the knees tracking over the toes, then drive back up to standing. Stand facing the camera, then turn half left or half right (about 45 degrees), with your whole body in frame.

1. Face the camera and hold your arms straight out to the sides (a T-pose; arms held lower and away from the body also start a set). A 3-second countdown starts.
2. During the countdown, turn to your angle until the turn cue clears, and get into position. If the countdown reaches 0 first, it waits until you are turned the right way.
3. To end the set, face the camera and hold the T-pose for about a second.$guide$
where id = 'squat';

update public.exercises set guide_text = $guide$Start in a high plank with the hands under the shoulders and the body in one straight line from head to heels. Lower until the chest is near the floor, with the shoulders about half an arm's length above the hands or lower, keeping the hips level with the shoulders, then press back up to straight arms. Place the camera low, then set up your plank turned halfway between facing it head-on and side-on (about 45 degrees), with your whole body in frame.

1. Face the camera and hold your arms straight out to the sides (a T-pose; arms held lower and away from the body also start a set). A 3-second countdown starts.
2. During the countdown, turn to your angle until the turn cue clears, and get into position. If the countdown reaches 0 first, it waits until you are turned the right way.
3. To end the set, face the camera and hold the T-pose for about a second.$guide$
where id = 'push-up';

update public.exercises set guide_text = $guide$Stand tall, step one foot forward, and lower straight down until the front knee is bent to about 90 degrees and the back knee drops toward the floor. Keep the torso upright, then push through the front heel back to standing. You may alternate legs. Turn fully left or right (90 degrees) so your side faces the camera, with your whole body in frame.

1. Face the camera and hold your arms straight out to the sides (a T-pose; arms held lower and away from the body also start a set). A 3-second countdown starts.
2. During the countdown, turn to your angle until the turn cue clears, and get into position. If the countdown reaches 0 first, it waits until you are turned the right way.
3. To end the set, face the camera and hold the T-pose for about a second.$guide$
where id = 'lunge';

update public.exercises set guide_text = $guide$Stand with a dumbbell in each hand, arms straight, elbows pinned to your sides. Curl the weight until the elbow is fully bent, then lower all the way back to a straight arm before the next rep. Keep the elbow still and do not swing the shoulder. Turn half left to work your right arm, or half right to work your left arm (about 45 degrees), so the working arm is nearest the camera.

1. Face the camera and hold your arms straight out to the sides (a T-pose; arms held lower and away from the body also start a set). A 3-second countdown starts.
2. During the countdown, turn to your angle until the turn cue clears, and get into position. If the countdown reaches 0 first, it waits until you are turned the right way.
3. To end the set, face the camera and hold the T-pose for about a second.$guide$
where id = 'bicep-curl';
